apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-aggregator-config
  namespace: mcp-aggregator
  labels:
    app.kubernetes.io/component: config
    app.kubernetes.io/name: mcp-aggregator
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:8080
  MCPAGGREGATOR__DATADIRECTORY: /data
